sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

env:
  - EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${EVAL}"
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./ads-b_ut

after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
email: false

